apiVersion: v1
kind: Namespace
metadata:
  name: mixer
---
apiVersion: v1
data:
  projectId: datcom-website-dev
  serviceName: mixer.endpoints.datcom-website-dev.cloud.goog
kind: ConfigMap
metadata:
  name: mixer-configmap-staging-8m2h9bm68f
  namespace: mixer
---
apiVersion: v1
data:
  bigquery.version: google.com:datcom-store-dev.dc_kg_2020_12_17_09_33_15
  bigtable.version: borgcron_2020_12_17_09_33_15
kind: ConfigMap
metadata:
  name: store-configmap-staging-6f7f9fmmck
  namespace: mixer
---
apiVersion: v1
kind: Service
metadata:
  name: mixer-service-staging
  namespace: mixer
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: mixer-grpc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mixer-grpc-staging
  namespace: mixer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mixer-grpc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mixer-grpc
    spec:
      containers:
      - args:
        - --bq_dataset
        - $(BIG_QUERY)
        - --bt_table
        - $(BIG_TABLE)
        - --bt_project
        - google.com:datcom-store-dev
        - --bt_instance
        - prophet-cache
        - --project_id
        - $(PROJECT_ID)
        env:
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              key: projectId
              name: mixer-configmap-staging-8m2h9bm68f
        - name: BIG_QUERY
          valueFrom:
            configMapKeyRef:
              key: bigquery.version
              name: store-configmap-staging-6f7f9fmmck
        - name: BIG_TABLE
          valueFrom:
            configMapKeyRef:
              key: bigtable.version
              name: store-configmap-staging-6f7f9fmmck
        image: gcr.io/datcom-ci/datacommons-mixer:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:12345
          initialDelaySeconds: 10
          periodSeconds: 5
        name: mixer
        ports:
        - containerPort: 12345
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:12345
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 2G
      - args:
        - --service
        - $(SERVICE_NAME)
        - --http_port
        - "8081"
        - --backend
        - grpc://127.0.0.1:12345
        - --cors_preset
        - basic
        - --rollout_strategy
        - managed
        - --healthz
        - healthz
        env:
        - name: SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              key: serviceName
              name: mixer-configmap-staging-8m2h9bm68f
        image: gcr.io/endpoints-release/endpoints-runtime:1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
        name: esp
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8081
          periodSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 1G
      serviceAccountName: mixer-ksa
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.global-static-ip-name: mixer-ip
    networking.gke.io/managed-certificates: mixer-certificate
  name: mixer-ingress-staging
  namespace: mixer
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: mixer-service-staging
          servicePort: 80
        path: /*
